### ISSUE TITLE
Two mails in Inbox instead of one (2.2.1)

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#28] opened 2019-08-22 06:22 UTC
On 2.2.1, mail1.json generates two emails in the Inbox. It should only be one.

**Comment by christian-bernet** [comment] 2019-08-28 13:10
Estimate 2 houres

**Comment by christian-bernet** [comment] 2019-09-09 12:32
we can not reproduce this situation. Maybe there was an error in the content that is now away.
@martindusinberre can you please verify.

**Comment by martindusinberre** [comment] 2019-09-10 09:03
Hi Christian: please reassign this to me once #51 has been fixed, and then I can test for the two-email problem on 2.2.1 again.

**Comment by christian-bernet** [comment] 2019-09-11 13:04
ok. Assigned now to you.

**Comment by martindusinberre** [comment] 2019-09-19 07:49
Sorry, the bug is still there. 
<img width="1362" alt="Screen Shot 2019-09-19 at 09 46 53" src="https://user-images.githubusercontent.com/53183999/65224078-c11e2680-dac2-11e9-8fd3-b01379e22156.png">

**Comment by christian-bernet** [comment] 2019-09-19 08:22
OK. Nemanja will check that also on Monday.

**Comment by christian-bernet** [comment] 2019-09-23 11:49
This situation is because of corrupt content after importing it with the importer. It is not because of wrong .json files. These are ok.
So this is also a result of the unstable importer.

Because this is wasting time for searching a certain bug and fix it, we decided to change the importer to a simple concept like this:
- For **test-system** with flag deletePlayerState = true: insert new topic and delete previous imported topic and delete players state
- for **production** with flag deletePlayerState = false: onnly insert mode and deactivate last imported topic

**Comment by christian-bernet** [comment] 2019-09-26 11:37
that is still open. If you do a second import it still creates two mails!
This is an importer bug. I will check that after my vacation.

**Comment by christian-bernet** [comment] 2019-10-15 14:36
can not reproduce it locally any more at this time. But importer needs still a bit of code changes.

**Comment by christian-bernet** [comment] 2019-10-18 13:42
Title of page 2.2.1 is "Chapter 2/5: Back home"

**Comment by christian-bernet** [comment] 2019-11-06 16:10
This bug ist still here:
![image](https://user-images.githubusercontent.com/41006947/68315630-58156100-00b8-11ea-98a9-f8af76036324.png)

**Comment by interrogator** [comment] 2019-11-13 12:17
@christian-bernet if and when this gets fixed, please let me know so I can version bump and redeploy livesintransit.org...

**Comment by christian-bernet** [comment] 2019-11-14 08:46
@interrogator I will fix this. But it is not that easy... I have looked several times at this issue.
And I will also do that on the beginning next week. But I am not sure if its fixed afterwards.
We have the problem only at the test-system. Not local on our dev-systems. So it is a little bit tricky to fix. But I will let you keep you up to date.

**Comment by christian-bernet** [comment] 2019-11-18 12:16
@interrogator it is planned to look at this next week. I will keep you up to date for that.

**Comment by christian-bernet** [comment] 2019-12-10 06:34
We postponed to do this....
It is now planned at the 19.12.19

**Comment by martindusinberre** [comment] 2019-12-10 07:59
OK, thanks for the update. Please do make sure that it's fixed no later than the 19th, as Pim's last day is on the 20th and we would all like to have the outstanding bugs from August fixed by then.

**Comment by christian-bernet** [comment] 2019-12-10 08:18
Thanks. For the feedback. So we will do it not later than the 19th.

**Comment by interrogator** [comment] 2019-12-10 09:39
@christian-bernet I don't know the backend well, but in terms of simplest fix, since mails are apparently exact duplicates, why not simply implement some check like (in python for brevity):

```python
set_of_mails = set()
if send_triggered(mail):
    if mail not in set_of_mails:
        send(mail)
        set_of_mails.add(mail)
    else:
        log("send mail triggered for duplicate msg', mail, debug_info')
```

Even if we don't know exactly why the problem occurs, at least this would stop it and collect info that might help us diagnose at a later stage. just a suggestion if you can't reproduce the problem...

**Comment by christian-bernet** [comment] 2019-12-16 10:32
@interrogator Great idea..... thanks.

**But happily:**
We test it again right now at the stage system and the problem is now also gone.
I assume that the problem was because of this instable importer.
But with the new version that problem is gone.
So, please retest it on your side and if everything is also ok, then please close it.

**Comment by martindusinberre** [comment] 2019-12-16 13:08
Hi Christian: great, thanks for the update. @lfeine could you please test this when you have time? Best, Martin

**Comment by interrogator** [comment] 2019-12-18 20:29
@christian-bernet are the changes related to this issue all in master branches? If so, this issue can be closed, as changes will go into next deployment.

**Comment by christian-bernet** [comment] 2019-12-18 20:59
@interrogator We did not change anything this week.
So, yes. this changes are all in master branch.

**Comment by lfeine** [comment] 2019-12-19 10:23
I'm not sure the previous messages mean that this still needs testing, but it doesn't show up to me anymore.

Unfortunately, when replying to the formerly duplicated E-Mail, the reply button appears to not do anything (no state changes, no loading bar). The mail is still sent however, and appears when swapping back from another mail or closing and opening the mail window. 

The error that appears in the console after pressing the reply button is:
`Error: Request failed with status code 400 app.js line 628 > eval:16:15` (Firefox 71.0)

**Comment by interrogator** [comment] 2019-12-19 11:35
@christian-bernet

**Comment by christian-bernet** [comment] 2019-12-19 13:17
I had a quick look on it.
![image](https://user-images.githubusercontent.com/41006947/71175173-2bcc3300-2267-11ea-9428-67cd94fa3f83.png)

There is an auto page transition when you reply to that mail which will fail, if you are not on page 2.2.1.
I can fix that on Monday. Unfortunately I can't do it today because we reserved the day for you last Monday.

**Comment by martindusinberre** [comment] 2019-12-20 15:45
@christian-bernet I had a look at this and I think it's a problem in the backend, right, not in the JSON files that I have. If so, then yes, please fix. The idea is that you shouldn't be able to transition from 2.2.1 to 2.2.2 unless you answer the email 2.2.1/mail1.json
Thanks, Martin

**Comment by christian-bernet** [comment] 2019-12-23 16:30
Bug for mail reply fixed: d3ff4ad8

**Comment by christian-bernet** [comment] 2020-01-07 13:09
We will have again a look at this tomorrow and see if we can fix the problem with the circle relationship for pagetransition on page 2.2.1

**Comment by martindusinberre** [comment] 2020-01-07 19:17
Many thanks, Christian. I'm not sure why there's a particular problem here, as it should be a similar functionality as on 2.2.8, where you can only transition to 2.2.9 if you answer the previously received email (2.1.6). Here's it's always functioned fine, so I'm a bit surprised if the transition from 2.2.1 to 2.2.2, dependent on answering 2.2.1/mail1, doesn't work. Or have I misunderstood? Anyway, let me know if it's faster to talk by phone about this tomorrow--I'm around all day after about 9am.

**Comment by nemtish** [comment] 2020-01-09 09:53
Hi @martindusinberre for this kind of situations where user should be transitioned automatically when replies to mail, you have to change "pageTransition.json" file like below:
"affectedMail": null, 
"buttonText": null

With this change button will stay invisible for the user and circle relationship (@christian-bernet mentioned) won't be problem

Pages where you have page transitions that are only unlocked (without auto-transition) when user reply to specific mail you leave like it is

**Comment by christian-bernet** [comment] 2020-01-09 12:15
Unfortunately we can not change the content ourself, because we do not have access to the content git anymore.
Add for the page 2.2.8 there is no auto-transition (if user reply to the mail) active.
Auto-transition can be activated if you add the pagetranstion in the mail.
As it is for mail1 on page 2.2.1.
![image](https://user-images.githubusercontent.com/41006947/72066890-02407d80-32e2-11ea-937d-7150706b9122.png)

**Closed** 2020-05-19 13:04 UTC
Labels: bug, high
