### ISSUE TITLE
Notebook inputs and notebook page titles not matching

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#13] opened 2019-08-13 08:32 UTC
I don't know whether I have inputted the json files wrongly for some of the notebook entries. Can you tell me how the email I am required to send on 2.2.8 (in order to pageTransition into 2.2.9) is saved to the notebook? I thought I had set it up so that the email content would be saved to notebook under the entry "Notes on Hall (email to Moira)" (see 2.2.8/notebookEntry1). Instead, the imageComponent from 2.3.1.1 has been saved under the notebook entry "Notes on Hall". The email to Moira from 2.2.8, meanwhile, has been saved in two places: in the "Race and Face" Exercise entry, and also in the "Notes while locked up" entry. Have I inputted json wrongly or is there a bug here? (Some of the time, e.g. on 2.3.6, the functionality is working fine, ie the textComponent saves to Notebook in the right notebookEntry; the problem may just therefore be with email text inputs to the Notebook.)

**Comment by martindusinberre** [comment] 2019-08-13 09:13
A quick update on this: On 2.4.2.1, the email that I'm required to send to Brian (mail3) in order to transition to 2.4.2.2 is saved into Notebook without a new entry. I guess this means I need to add a notebookEntry json file in order for it to be saved as a new entry. But can you please look at why the email that I previously sent about Stuart Hall (2.2.8 into 2.2.9) is one again appearing in the Notebook? This seems to be an error.

**Comment by christian-bernet** [comment] 2019-08-13 14:42
yes. You have to add a new notebook-Entry if you want to have the e-mail shown in a speperate entry.

On page 2.2.9 an email is sent, but not shown in the notebook...
If you want to show the email at page 2.2.9 you have to add   "showInNotebook": true, in the mail1.json on page 2.2.9.

If you find the same mail twice in the notebook, please write me the page on which the mail is generated, so that I can reproduce the situation

**Comment by martindusinberre** [comment] 2019-08-13 17:57
Sorry, there are several issues here:
i) In order to leave 2.2.8, I have to reply to the email on 2.1.6/mail1. This json file is already inputted as "showInNotebook": true. [The mail on 2.2.9 isn't the problem here]
ii) But when I press "send" to my reply to 2.1.6/mail1, the content of my reply is not saved where I want it in the notebook, ie in 2.2.8/notebookEntry1 with the title "Notes on Hall (email to Moira)". Why not?
iii) Instead, the content of my reply to 2.1.6/mail1 (which is generated on 2.2.8) is saved in the notebook in a completely different place, under the Notebook entry "Race and Face Exercise" (ie from chapter 1). Why?
iv) Later, my reply to 2.1.6/mail1 (generated on 2.2.8) is also saved in the Notebook under "Notes while locked up" (ie chapter 3, 2.3.4). This is wrong.
v) Later again, my reply to 2.1.6/mail1 (generated on 2.2.8) also appears again in the Notebook when I transition from 2.4.2.1 to 2.4.2.2 (ie chapter 4). Again, why?
It seems to me from playing more today that **there is a problem with the input from mail replies being saved several times to Notebook**. I'll keep an eye on this tomorrow but that would seem to be the main issue now.

**Comment by christian-bernet** [comment] 2019-08-14 15:07
This is a backend bug. I have to fix that.

**Comment by christian-bernet** [comment] 2019-08-14 15:24
The reply of the mail should be added to the last notebook entry that was added in the notebook.

**Comment by christian-bernet** [comment] 2019-08-28 13:29
Estimate 2 hours

**Comment by christian-bernet** [comment] 2019-09-09 15:05
If you reply to a mail two times it now shows both reply in two notebook entries, which is not that good.

I think we should change the state model to that:
- new reference from notebookContent to MailReply
- change reference from notebookContent to MailState to Mail instead


![image](https://user-images.githubusercontent.com/41006947/64542498-f50b8600-d323-11e9-839e-aadb83ffebd6.png)

**Comment by nemtish** [comment] 2019-09-10 12:20
Fixed with: https://github.com/uzh/marugoto/commit/e5456494635cc4a745ec4fbf1df7874ff7e0df30

**Comment by christian-bernet** [comment] 2019-09-11 13:21
frontend needs to be changed also!

**Comment by martindusinberre** [comment] 2019-09-19 08:20
@lfeine @Helena-LiT Can you please check this as well? But I think it is fine. If you're happy with it too, please close the issue on Friday.

**Comment by Helena-LiT** [comment] 2019-09-21 20:43
I no longer see the problem that emails are saved in the notebook in different places and several times, so that issue seems to be resoved. 

However, there is still the issue that instead of the email from 2.2.8 the imageComponent from 2.3.1.1 is saved under the notebook entry "Notes on Hall". Is there perhaps something wrong with the way the notebook entry for that page is set up?
2.2.8/notebookEntry1:
```
{
  "id": null,
  "title": "Notes on Hall (email to Moira)",
  "page": null
}
```

Compared to this the notebook entry for email  2.4.2.1 works fine:
2.4.2.1/notebookEntry1

```
{
  "id": null,
  "title": "Emails",
  "text": null,
  "page": "chapter4/2.4.2.1/page.json",
  "dialogResponse": null,
  "mail": null,
  "personalNotes": null,
  "addToPageStateAt": "enter"
}
```

**Comment by martindusinberre** [comment] 2019-09-22 18:21
Thanks, Lena: I think this is a bug. I'll record it as a separate issue and close this one.

**Comment by martindusinberre** [comment] 2019-09-22 18:34
Actually I don't think it's a bug--I've pushed some changes to json.

**Comment by christian-bernet** [comment] 2019-09-23 06:53
The email reply will be store on that last notebook entry where the user is at that time.
I think otherwise it is confusing for the player if he has it not on the last notebook entry.

**Comment by martindusinberre** [comment] 2019-09-23 07:05
Yes, that's fine--thanks.

**Comment by martindusinberre** [comment] 2019-09-26 12:47
@Helena-LiT Could you possibly check this again now that I've pushed some changes to the json files? I'm sure it's not a bug but rather an input mistake from my side. Thanks, martin

**Closed** 2019-09-30 17:50 UTC
Labels: high
